package main

import (
	"fmt"
	"github.com/JuanValero25/EasyDynamoDB/easydynamoclient"
	"os"
)

type Account struct {
	AccountId       string      `json:"AccountId,omitempty" AutoGenerated:"true" dynamoHasKey:"AccountId"`
	InterestingData string      `json:"InterestingData,omitempty" dynamoDbAttribute:"InterestingData"`
	PhoneNumber     string      `json:"phone,omitempty" dynamoDbAttribute:"PhoneNumber"`
	SomeRandomVAlue structValue `json:"someval,omitempty" dynamoDbAttribute:"SomeRandomVAlue"`
}

type structValue struct {
	SomeValue  string `json:"SomeValue,omitempty"`
	OtherValue string `json:"OtherValue,omitempty"`
}

func (acc Account) TableName() string {
	return "Account"
}

func main() {

	os.Setenv("ENVIRONMENT", "dev")
	//acc := Account{AccountId: "1d98617a-ccc6-4490-9477-e5a8387b538b", InterestingData: "updateValue"}
	//easydynamoclient.New().Update(acc)
	acc := Account{}
	easydynamoclient.NewWithTableObject(acc).GetItemByHashKey("1d98617a-ccc6-4490-9477-e5a8387b538b", &acc)
	fmt.Println("final account")
	fmt.Println(acc)

}
