package easydynamoclient

import (
	"github.com/JuanValero25/EasyDynamoDB/lambdaconfig"
	"reflect"
)

func ProcessTableInfo(tableObject lambdaconfig.TableInfo) {

	t := reflect.TypeOf(tableObject)

	for i := 0; i < t.NumField(); i++ {
		_, trued := t.Field(i).Tag.Lookup("AutoGenerated")
		if trued {
			tableObject.ReflectedValue().Field(i).SetString("asd")

		}
	}

}
