package easydynamoclient

import (
	"github.com/JuanValero25/EasyDynamoDB/lambdaconfig"
	"github.com/satori/go.uuid"
	"reflect"
)

func ProcessTableInfo(tableObject lambdaconfig.TableInfo) {

	t := reflect.TypeOf(tableObject).Elem()

	for i := 0; i < t.NumField(); i++ {
		_, trued := t.Field(i).Tag.Lookup("AutoGenerated")
		if trued {
			ui, _ := uuid.NewV4()
			reflect.ValueOf(tableObject).Elem().Field(i).SetString(ui.String())

		}
	}

}
