package easydynamoclient

import (
	"github.com/JuanValero25/EasyDynamoDB/lambdaconfig"
	"github.com/satori/go.uuid"
	"reflect"
)

func ProcessTableInfo(tableObject lambdaconfig.TableInfo) *lambdaconfig.TableInfo {

	ui, err := uuid.NewV4()
	if err != nil {

	}
	t := reflect.TypeOf(tableObject)
	for i := 0; i < t.NumField(); i++ {
		_, trued := t.Field(i).Tag.Lookup("AutoGenerated")
		if trued {
			reflect.ValueOf(tableObject).Field(i).SetString(ui.String())
		}

	}

}
